config-version: 2

schemachange:

  vars:
    CUSTOMER_TABLE: 'CUSTOMERS'
    RETAILERS_TABLE: 'RETAILERS'
    ORDERS_TABLE: 'ORDERS'
    DATABASE : BRONZE
    SCHEMA : DEV
    RETAILERS_TABLE: "RETAILERS"
    ORDERS_TABLE: "ORDERS"
    LOG_TABLE: "PROCESS_LOGS"
    DEFAULT_STATUS: "PENDING"
    CREATED_BY: "SYSTEM"


  create-change-history-table: true
  change-history-table: 'BRONZE.DEV.CHANGE_HISTORY'
  autocommit: true
