config-version: 2


vars:
  CUSTOMER_TABLE: 'CUSTOMERS'
  RETAILERS_TABLE: 'RETAILERS'
  ORDERS_TABLE: 'ORDERS'
  DATABASE : BRONZE
  SCHEMA : DEV



create-change-history-table: true
autocommit: true
