USE {{ DATABASE }};
USE SCHEMA {{ SCHEMA }};

CREATE OR REPLACE TABLE {{ DATABASE }}.{{ SCHEMA }}.{{ CUSTOMER_TABLE }} (
    CUSTOMER_ID INT,
    NAME STRING,
    EMAIL STRING,
    CREATED_AT TIMESTAMP
);
