name: Deploy Migrations

on:
  push:
    branches:
      - dev
      - test
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    if: github.ref_name == 'dev'
    environment: dev
    
    name: Deploy to DEV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Schemachange
        run: |
          python -m pip install --upgrade pip
          pip install schemachange

      - name: Write connections for Sotred_Procs
        run: |
          # bronze
          mkdir -p stored_procs/migrations/config
          : > stored_procs/migrations/config/connections.toml
          cat > stored_procs/migrations/config/connections.toml <<EOF
          [snowflake]
          SNOWFLAKE_ACCOUNT = ${{ secrets.ACCOUNT }}
          SNOWFLAKE_USER = ${{ secrets.USER }}
          SNOWFLAKE_ROLE = ACCOUNTADMIN
          SNOWFLAKE_WAREHOUSE = COMPUTE_WH
          SNOWFLAKE_DATABASE = BRONZE
          SNOWFLAKE_SCHEMA = TEST
          EOF
          chmod 600 stored_procs/migrations/config/connections.toml

        

      - name: Debug connections.toml content per layer
        run: |
          for layer in bronze silver gold; do
            echo "connections.toml for stored_procs:"
            cat "$GITHUB_WORKSPACE/stored_procs/migrations/config/connections.toml"
          done

      - name: Deploy nowww
        run: |

          echo "Deploying stored_procs layer in Dev Env..."
          schemachange deploy \
            -f "$GITHUB_WORKSPACE/stored_procs/migrations" \
            --config-folder "$GITHUB_WORKSPACE/stored_procs/migrations/config" \
            --config-file-name schemachange-config.yml \
            --connections-file-path "$GITHUB_WORKSPACE/stored_procs/migrations/config/connections.toml" \
            --connection-name snowflake \
            --snowflake-private-key-file "$GITHUB_WORKSPACE/stored_procs/migrations/config/rsa_key.p8 \
            --change-history-table "BRONZE.DEV.CHANGE_HISTORY" \
            --query-tag "schemachange-stored_procs" \
            --verbose
          

  deploy-test:
    runs-on: ubuntu-latest

    if: github.ref_name == 'test'
    environment: test
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.PASSWORD }}
      SNOWFLAKE_ROLE: ACCOUNTADMIN
      SNOWFLAKE_WAREHOUSE: COMPUTE_WH
      SNOWFLAKE_DATABASE: BRONZE
      SNOWFLAKE_SCHEMA: TEST

    

    name: Deploy to TEST
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Schemachange
        run: |
          python -m pip install --upgrade pip
          pip install schemachange

      - name: Write connections inside folder
        run: |
          mkdir -p stored_procs/migrations/config
          : > stored_procs/migrations/config/connections.toml
          cat > stored_procs/migrations/config/connections.toml <<EOF
          [snowflake]
          account   = "${{ secrets.ACCOUNT }}"
          user      = "${{ secrets.USER }}"
          password  = "${{ secrets.PASSWORD }}"
          role      = "${{ secrets.ROLE }}"
          warehouse = "${{ secrets.WAREHOUSE }}"
          database  = "BRONZE"
          schema    = "TEST"
          EOF
          chmod 600 stored_procs/migrations/config/connections.toml


      - name: Debug connections.toml content per layer
        run: |
          for layer in bronze silver gold; do
            echo "connections.toml for stored_procs:"
            cat "$GITHUB_WORKSPACE/stored_procs/migrations/config/connections.toml"
          done

      - name: Deploy nowww
        run: |
          
          schemachange deploy \
            -f "$GITHUB_WORKSPACE/stored_procs/migrations" \
            --config-folder "$GITHUB_WORKSPACE/stored_procs/migrations/config" \
            --config-file-name schemachange-config.yml \
            --connections-file-path "$GITHUB_WORKSPACE/stored_procs/migrations/config/connections.toml" \
            --connection-name snowflake \
            --change-history-table "stored_procs.TEST.CHANGE_HISTORY" \
            --query-tag "schemachange-stored_procs" \
            --verbose
        


  deploy-prod:
    runs-on: ubuntu-latest

    if: github.ref_name == 'main'
    environment: prod
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.PASSWORD }}
      SNOWFLAKE_ROLE: ACCOUNTADMIN
      SNOWFLAKE_WAREHOUSE: COMPUTE_WH
      SNOWFLAKE_DATABASE: BRONZE
      SNOWFLAKE_SCHEMA: PROD

    

    name: Deploy to PROD
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Schemachange
        run: |
          python -m pip install --upgrade pip
          pip install schemachange

      - name: Write connections for bronze/silver/gold
        run: |
          # bronze
          mkdir -p stored_procs/migrations/config
          : > stored_procs/migrations/config/connections.toml
          cat > stored_procs/migrations/config/connections.toml <<EOF
          [snowflake]
          account   = "${{ secrets.ACCOUNT }}"
          user      = "${{ secrets.USER }}"
          password  = "${{ secrets.PASSWORD }}"
          role      = "${{ secrets.ROLE }}"
          warehouse = "${{ secrets.WAREHOUSE }}"
          database  = "BRONZE"
          schema    = "TEST"
          EOF
          chmod 600 stored_procs/migrations/config/connections.toml

          
          
      - name: Debug connections.toml content per layer
        run: |
          for layer in bronze silver gold; do
            echo "connections.toml for stored_procs:"
            cat "$GITHUB_WORKSPACE/stored_procs/migrations/config/connections.toml"
          done

      - name: Deploy nowww
        run: |
          for layer in bronze silver gold; do
            echo "Now Deploying stored_procs layer In prod Env Be carefull friend..."
            schemachange deploy \
              -f "$GITHUB_WORKSPACE/stored_procs/migrations" \
              --config-folder "$GITHUB_WORKSPACE/stored_procs/migrations/config" \
              --config-file-name schemachange-config.yml \
              --connections-file-path "$GITHUB_WORKSPACE/stored_procs/migrations/config/connections.toml" \
              --connection-name snowflake \
              --change-history-table "stored_procs.PROD.CHANGE_HISTORY" \
              --query-tag "schemachange-stored_procs" \
              --verbose
          done