name: Deploy Migrations

on:
  push:
    branches:
      - dev
      - test
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    if: github.ref_name == 'dev'
    environment: dev

    env:
      SNOWFLAKE_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ vars.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_AUTHENTICATOR: "snowflake_jwt"

    
    name: Deploy to DEV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Schemachange
        run: |
          python -m pip install --upgrade pip
          pip install schemachange

      - name: Create private key file
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem


      - name: Deploy nowww
        run: |

          echo "Deploying stored_procs layer in Dev Env..."
          schemachange deploy \
            -f "$GITHUB_WORKSPACE/stored_procs/migrations" \
            -m "$GITHUB_WORKSPACE/stored_procs/migrations/scripts" \
            --config-folder "$GITHUB_WORKSPACE/stored_procs/migrations/config" \
            --config-file-name schemachange-config.yml \
            --snowflake-private-key-path private_key.pem \
            --query-tag "schemachange-stored_procs" \